### ISSUE TITLE
Unable to set arbitrary environment values

### ISSUE THREAD

**Issue by zavyrylin** [funbox/init-exporter#20]
A attempt to export simple procfile v2 with command section like the following:
```yaml
commands:
  app1:
    env:
      JAVA_OPTS: '"-Xms512m -Xmx1g -XX:+HeapDumpOnIutOfMemoryError"'
      LOADER_SYSTEM: true
    command: bin/run-something
```
leads to export failure with error message:
```
Errors while application validation:
- Environment variable value "-Xms512m -Xmx1g -XX:+HeapDumpOnOutOfMemoryError" is insecure and can't be accepted
```

I believe it is quite common to setup some configuration through environment variables defined that way, so it seems that validation rules applied on export are too strict.
