### ISSUE TITLE
[Feature Request] Add global log file option

### ISSUE THREAD

**Issue by vassilevsky** [funbox/init-exporter#52]
Hi 👻

It would have been nice for low-volume services to have a single log file for all processes.

Now it requires repeating the `log` option in each process:

```yaml
# Procfile.v2

commands:
  foo:
    command: foo
    log: log/common.log
  bar:
    command: bar
    log: log/common.log
```

Common log option would have been more convenient:

```yaml
# Procfile.v2

log_file: log/common.log

commands:
  foo:
    command: foo
  bar:
    command: bar
```

Thanks 🙏

**Comment by andyone** [comment]
Nice idea! I will implement this feature in the next version. Stay tuned for updates.

**Comment by andyone** [comment]
I just found that I had already added this feature 😄
You can define the global log and redefine it if required. Like this:

```yaml
log: log/common.log

commands:
  foo:
    command: foo
    log: log/foo.log

  bar:
    command: bar
```
